name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: ./01 Starting Project
      - name: Lint code
        run: npm run lint
        working-directory: ./01 Starting Project
      - name: Test code
        run: npm run test
        working-directory: ./01 Starting Project
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-name: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: ./01 Starting Project
      - name: Build website
        run: npm run build
        working-directory: ./01 Starting Project
      - name: Publish  JS File name
        id: publish
        run: |
          FILE=$(find "./01 Starting Project/dist" -type f -name "*.js" | head -n 1)
          echo "script-file=$FILE" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            ./01 Starting Project/dist
          #  ./01 Starting Project/package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: List files
        run: ls
      - name: Output file name
        run: echo "${{ needs.build.outputs.script-name }}"
      - name: Deploy
        run: echo "Deploying..."
